version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: itnpru64
      MYSQL_PASSWORD: itnpru6438@
      MYSQL_DATABASE: activityDB
      MYSQL_ROOT_PASSWORD: rootpassword 