version: "3.1"

services:
  db:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile.mysql  # Specify the Dockerfile name
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: itnpru64
      MYSQL_PASSWORD: itnpru6438@
      MYSQL_DATABASE: activityDB
      MYSQL_ROOT_PASSWORD: rootpassword
